---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: upf-n3
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eth3",
      "mode": "passthru",
      "ipam": {
        "type": "host-local",
        "subnet": "10.1.130.0/24",
        "rangeStart": "10.1.130.70",
        "rangeEnd": "10.1.130.70"
      }
    }

# ---
# apiVersion: k8s.cni.cncf.io/v1
# kind: NetworkAttachmentDefinition
# metadata:
#   name: upf-n4
# spec:
#   config: |
#     {
#       "cniVersion": "0.3.1",
#       "type": "macvlan",
#       "master": "eth4",
#       "mode": "passthru",
#       "ipam": {
#         "type": "host-local",
#         "subnet": "10.1.140.0/24",
#         "rangeStart": "10.1.140.70",
#         "rangeEnd": "10.1.140.70"
#       }
#     }

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: upf-n6
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eth5",
      "mode": "passthru",
      "ipam": {
        "type": "host-local",
        "subnet": "10.1.160.0/24",
        "rangeStart": "10.1.160.70",
        "rangeEnd": "10.1.160.70"
      }
    }
